### ISSUE TITLE
Leader that crashes and recovers doesn't auto-sync - HB nacks

### ISSUE THREAD

**Issue by yacovm** [hyperledger-labs/SmartBFT#337]
Currently, when followers receive heartbeats from the leader and they notice they are behind - they sync.

However, if a leader has crashed and a new leader has been elected - that leader will still think it's a leader and will only sync with requests. 

We need a mechanism that makes the old leader detect it's not the leader anymore and sync.

I think that ideally we can have followers send a nack to the heart beat of a leader that is not the leader, and the leader can act on these nacks if received enough (f+1) nacks.

**Comment by tock-ibm** [comment]
One problem with this proposal is that even if after the new view the old-recovered-leader syncs, with the current sync mechanism it will not discover the new view number, as the new view is not in the decided blockchain (i.e. snapshots, essentially), but only in the WAL of other correct peers. 

So what you are suggesting is a parallel 3-phase consensus mechanism... I am hesitant to go this way.

I think that the core of the problem is because our state-transfer is partial - compared to pbft and  bft-smart - we do not bring the most recent part of the "log" (in the general sense), which in our case is the WAL, in the sync. We only bring what was decided and logged in the app's log (i.e. get the blocks form Fabric). 

Therefore, one way to solve problem, and possibly other problems that we did not tackle yet, is to improve the sync. The controller sync() would call the Fabric (dependency Synchronizer) Sync() that catches up and brings the last decision. Then (or in parallel), it could call a "WAL Sync" (for lack of a better term). The WAL-sync would bring the WAL of all peers, and the node can then search for f+1 identical responses and make progress from there. This would give you a complete log from which to recover. 

Another way would be for the new leader after a view change, and in case there are no new batches to propose, to propose a NO-OP block, that would go all the way to the app's log (i.e. would be written a fabric block). This would make our current sync deal with the problem. I don't know if fabric can handle this. This is undesirable from several aspects; just bringing this up for the completeness of discussion.

**Comment by yacovm** [comment]
This issue deals with handling only cases in which there have been a decision in the new view. 
Syncing a view that didn't have a decision is orthogonal to this issue.

**Comment by tock-ibm** [comment]
Following group discussion, see related issues: #350 #351
