### ISSUE TITLE
Refactor Assembler interface

### ISSUE THREAD

**Issue by C0rWin** [hyperledger-labs/SmartBFT#88]
At the moment, `Assembler` interface defined as

```
type Assembler interface {
	AssembleProposal(metadata []byte, requests [][]byte) (nextProp bft.Proposal, remainder [][]byte)
}
```

where it returns next proposal to consent on and reminder in case there was a configuration update or other application level need to split requests into several proposals. However I think this is not sufficient as there might be a case, where we have to split into two proposals but cannot return a reminder. An example: configuration update transaction which might come in the middle, hence there are two alternatives:

1. We can split into proposal and reminder where reminder will include configuration update. On the next call though it will have to split again, configuration update and rest of the requests.

2. Instead of returning one proposal we can return a slice of proposals and reminder in such way API consumer will have to consent on two or more proposals before assembling next. 

@yacovm @HagarMeir @tock-ibm what should be preferable option? We can choose for now option 1, since less intrusive, basically doesn't require any changes or to turn API into more generic allowing option 2.

Suggested change for option 2 would be

```
type Assembler interface {
	AssembleProposal(metadata []byte, requests [][]byte) (nextProp []bft.Proposal, remainder [][]byte)
}
```

**Comment by yacovm** [comment]
When we have a config transaction in the middle of a batch we just batch everything up until and including the config transaction, and put the rest into a reminder, and then in the next batch, we'll only have the config transaction. 

The reminder always takes preference over anything else in the request pool so we don't have a starvation problem.

I think we should keep what we're doing because having a config transaction is:

1. Rare
2. Disruptive any way you look at it, because it is followed by a complete validation of the entire request pool.

**Comment by C0rWin** [comment]
Fair enough, closing.
